#!/usr/bin/env python3
"""Centralized trading parameters and risk thresholds."""

INITIAL_CAPITAL = 100000.0  # 初始资金 $100,000

MAX_RISK_PER_TRADE = 0.02
MAX_POSITION_PER_SYMBOL = 10000
MAX_POSITION_RATIO = 0.20

DEFAULT_STOP_LOSS_PCT = 0.03

MACD_FAST_PERIOD = 12
MACD_SLOW_PERIOD = 26
MACD_SIGNAL_PERIOD = 9
MACD_WARMUP_BARS = 30

MIN_SIGNAL_CONFIDENCE = 0.3
ALLOW_DUPLICATE_TRADES = False

ACCOUNT_UPDATE_INTERVAL = 60
CLIENT_ID = 982
