# Generated by ChatGPT on 2025-10-17
from __future__ import annotations

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulatedOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=16)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        max_length=4,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop"),
                        ],
                        default="MARKET",
                        max_length=16,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("limit_price", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("fill_price", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("WORKING", "Working"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="FILLED",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
